### ISSUE TITLE
CPU-BlockLightning does not work

### ISSUE THREAD

**Issue by ghost** [technistguru/PixelDot#1]
**Issue:**
CPU-BlockLightning are showed as regular sprites.

![image](https://user-images.githubusercontent.com/49753411/127772183-764ca293-ed82-46d9-9245-17e50c8a826c.png)
![image](https://user-images.githubusercontent.com/49753411/127772189-f875f2b7-5555-4986-8dcb-d9eb16a6fca5.png)

**Comment by Texnist** [comment]
Does it still function properly? C# plugins can be glitchy sometimes. It seems like Godot isn't recognizing them as custom nodes and giving them the appropriate icons, in which case there's nothing I can do to fix this.
